

const data = {
  users: [
    {
        _id: 1,
        name: 'Jon doe',
        profession:'Graphic Designer',
        image: './image/pic-4.png',
        ReviewUs: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium iusto id autem possimus assumenda at ut saepe.',
        RateUs: 3
      },
      {
        _id: 2,
        name: 'Yusuf Lateef',
        image: './image/pic-3.png',
        profession:'Doctor',
        ReviewUs:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium iusto id autem possimus assumenda at ut saepe.',
        RateUs: 2
      },
      {
          _id: 3,
        name: 'Emmanuel Lateef',
        image: './image/pic-2.png',
        profession:'Doctor',
        ReviewUs:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium iusto id autem possimus assumenda at ut saepe.',
        RateUs: 4
      },
      {
        _id: 4,
        name: 'Boss Man',
        image: './image/pic-1.png',
        profession:'Farmer',
        ReviewUs: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium iusto id autem possimus assumenda at ut saepe.',
        RateUs: 4.5
      },
    ],
  

    products: [
        {
            _id: '1',
            name: 'car1',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/vehicle-1.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            _id: '2',
            name: 'car2',
            model: 'Rolls Royce',
            category: 'Car',
            year: '2020',
            engine: 'petrol',
            speed: '183mph',
            price: 52000,
            color: 'red',
            image: './image/vehicle-2.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            _id: '3',
            name: 'car3',
            model: 'Audi',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/vehicle-3.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            _id: '4',
            name: 'car4',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/vehicle-4.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            _id: '5',
            name: 'car5',
            model: 'Rolls Royce',
            category: 'Car',
            year: '2020',
            engine: 'petrol',
            speed: '183mph',
            price: 52000,
            color: 'red',
            image: './image/vehicle-5.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            _id: '6',
            name: 'car6',
            model: 'Audi',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/vehicle-6.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            _id: '7',
            name: 'car7',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-1.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car',
            ShowUnder: 'Featured1'
        },
        {
            _id: '8',
            name: 'car8',
            model: 'Rolls Royce',
            category: 'Car',
            year: '2020',
            engine: 'petrol',
            speed: '183mph',
            price: 52000,
            color: 'red',
            image: './image/car-2.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured1'
        },
        {
            _id: '9',
            name: 'car9',
            model: 'Audi',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-3.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured1'
        },
        {
            _id: '10',
            name: 'car10',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-4.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured1'
        },
        {
            _id: '11',
            name: 'car11',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-5.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured2'
        },
        {
            _id: '12',
            name: 'car2',
            model: 'Rolls Royce',
            category: 'Car',
            year: '2020',
            engine: 'petrol',
            speed: '183mph',
            price: 52000,
            color: 'red',
            image: './image/car-6.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured2'
        },
        {
            _id: '13',
            name: 'car13',
            model: 'Audi',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-7.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured2'
        },
        {
            _id: '14',
            name: 'car14',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-8.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured2'
        },
    ],
};
export default data;
