
const bcrypt =require('bcryptjs'); 

const data = {
  users: [
    {
      name: 'Jon doe',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: true,
      profession:'',
      image: './image/pic-4.png',
      ReviewUs: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium iusto id autem possimus assumenda at ut saepe.',
      RateUs: 3
    },
    {
      name: 'Yusuf Lateef',
      email: 'Yusuf@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
      image: './image/pic-3.png',
      profession:'Doctor',
      ReviewUs:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium iusto id autem possimus assumenda at ut saepe.',
      RateUs: 2
    },
    {
      name: 'Emmanuel Lateef',
      email: 'Emmanuel@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
      image: './image/pic-2.png',
      profession:'Doctor',
      ReviewUs:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium iusto id autem possimus assumenda at ut saepe.',
      RateUs: 4
    },
    {
      name: 'Boss Man',
      email: 'Boss@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
      image: './image/pic-1.png',
      profession:'Farmer',
      ReviewUs:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam incidunt quod praesentium iusto id autem possimus assumenda at ut saepe.',
      RateUs: 4.5
    },
  ],

    products: [
        {
            name: 'car1',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/vehicle-1.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            name: 'car2',
            model: 'Rolls Royce',
            category: 'Car',
            year: '2020',
            engine: 'petrol',
            speed: '183mph',
            price: 52000,
            color: 'red',
            image: './image/vehicle-2.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            name: 'car3',
            model: 'Audi',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/vehicle-3.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            name: 'car4',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/vehicle-4.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            name: 'car5',
            model: 'Rolls Royce',
            category: 'Car',
            year: '2020',
            engine: 'petrol',
            speed: '183mph',
            price: 52000,
            color: 'red',
            image: './image/vehicle-5.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            name: 'car6',
            model: 'Audi',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/vehicle-6.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Popular'
        },
        {
            name: 'car7',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-1.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car',
            ShowUnder: 'Featured1'
        },
        {
            name: 'car8',
            model: 'Rolls Royce',
            category: 'Car',
            year: '2020',
            engine: 'petrol',
            speed: '183mph',
            price: 52000,
            color: 'red',
            image: './image/car-2.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured1'
        },
        {
            name: 'car9',
            model: 'Audi',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-3.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured1'
        },
        {
            name: 'car10',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-4.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured1'
        },
        {
            name: 'car11',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-5.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured2'
        },
        {
            name: 'car12',
            model: 'Rolls Royce',
            category: 'Car',
            year: '2020',
            engine: 'petrol',
            speed: '183mph',
            price: 52000,
            color: 'red',
            image: './image/car-6.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured2'
        },
        {
            name: 'car13',
            model: 'Audi',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-7.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured2'
        },
        {
            name: 'car14',
            model: 'Toyota',
            category: 'Car',
            year: '2021',
            engine: 'petrol',
            speed: '183mph',
            price: 62000,
            color: 'red',
            image: './image/car-8.png',
            type: 'automatic',
            rating: 4.5,
            oldNew: 'new',
            numReviews: 5,
            description: 'high durable car', 
            ShowUnder: 'Featured2'
        },
    ],
};

module.exports = data;